### ISSUE TITLE
지도에서 피드 리스트 앤드 페이지까지 진입하는 로직 구성

### ISSUE THREAD

**Issue by ChoMk** [Basicbug/Bikini_Android#7]
##  **시나리오**

스몰 피드 클릭 -> 앨범 피드 진입 -> 앨범 피드 클릭 -> 디테일 피드 리스트 진입 

##  **TODO**

- [ ]  앨범 피드 페이지 구성
- [ ]  디테일 피드 리스트 구성
- [ ]  지도에서 앤드 피드 리스트까지 연결

**Comment by ChoMk** [comment]
해당 이슈는 클로즈하고 좀 더 나눠서 이슈 등록할게유
